name: CI
on: [push]
jobs:
  verify_java_7:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
        - 7
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/socket.io-client-java/socket.io-client-java/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
    - run: touch starting_verifyjava7_uses-checkout_15
    - run: rm starting_verifyjava7_uses-checkout_15
    - uses: actions/checkout@v2
    - run: touch starting_verifyjava7_Setupjava_16
    - run: rm starting_verifyjava7_Setupjava_16
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - run: touch starting_verifyjava7_CacheMavenpackages_20
    - run: rm starting_verifyjava7_CacheMavenpackages_20
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - run: touch starting_verifyjava7_SetupNodejs_26
    - run: rm starting_verifyjava7_SetupNodejs_26
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: touch starting_verifyjava7_RuntheMavenverifyphase_30
    - run: rm starting_verifyjava7_RuntheMavenverifyphase_30
    - name: Run the Maven verify phase
      run: mvn verify -Dgpg.skip=true
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: Execute py script # run file
      if: always()
      run: |
        python .github/workflows/script.py
    - name: Pushes analysis to another repository
      if: always()
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'optimizing-ci-builds-ci-analysis'
        destination-github-username: 'UT-SE-Research'
        destination-repository-name: 'ci-analyzes'
        target-branch: '1675896667'
        target-directory: 'socket.io-client-java/.github/workflows/ci/verifyjava7'
  verify_java_8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
        - 8
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/socket.io-client-java/socket.io-client-java/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
    - run: touch starting_verifyjava8_uses-checkout_39
    - run: rm starting_verifyjava8_uses-checkout_39
    - uses: actions/checkout@v2
    - run: touch starting_verifyjava8_Setupjava_40
    - run: rm starting_verifyjava8_Setupjava_40
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - run: touch starting_verifyjava8_CacheMavenpackages_44
    - run: rm starting_verifyjava8_CacheMavenpackages_44
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - run: touch starting_verifyjava8_SetupNodejs_50
    - run: rm starting_verifyjava8_SetupNodejs_50
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: touch starting_verifyjava8_RuntheMavenverifyphase_54
    - run: rm starting_verifyjava8_RuntheMavenverifyphase_54
    - name: Run the Maven verify phase
      run: mvn verify -Dgpg.skip=true
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: Execute py script # run file
      if: always()
      run: |
        python .github/workflows/script.py
    - name: Pushes analysis to another repository
      if: always()
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'optimizing-ci-builds-ci-analysis'
        destination-github-username: 'UT-SE-Research'
        destination-repository-name: 'ci-analyzes'
        target-branch: '1675896667'
        target-directory: 'socket.io-client-java/.github/workflows/ci/verifyjava8'
  verify_java_11:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
        - 11
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/socket.io-client-java/socket.io-client-java/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
    - run: touch starting_verifyjava11_uses-checkout_63
    - run: rm starting_verifyjava11_uses-checkout_63
    - uses: actions/checkout@v2
    - run: touch starting_verifyjava11_Setupjava_64
    - run: rm starting_verifyjava11_Setupjava_64
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - run: touch starting_verifyjava11_CacheMavenpackages_68
    - run: rm starting_verifyjava11_CacheMavenpackages_68
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - run: touch starting_verifyjava11_SetupNodejs_74
    - run: rm starting_verifyjava11_SetupNodejs_74
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: touch starting_verifyjava11_RuntheMavenverifyphase_78
    - run: rm starting_verifyjava11_RuntheMavenverifyphase_78
    - name: Run the Maven verify phase
      run: mvn verify -Dgpg.skip=true
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: Execute py script # run file
      if: always()
      run: |
        python .github/workflows/script.py
    - name: Pushes analysis to another repository
      if: always()
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'optimizing-ci-builds-ci-analysis'
        destination-github-username: 'UT-SE-Research'
        destination-repository-name: 'ci-analyzes'
        target-branch: '1675896667'
        target-directory: 'socket.io-client-java/.github/workflows/ci/verifyjava11'

