name: CI

on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [7, 8, 11]

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work/socket.io-client-java/socket.io-client-java/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
      - run: touch starting_verify_uses-checkout_18
      - run: rm starting_verify_uses-checkout_18
      - uses: actions/checkout@v2
      - run: touch starting_verify_Setupjava_19
      - run: rm starting_verify_Setupjava_19
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: touch starting_verify_CacheMavenpackages_23
      - run: rm starting_verify_CacheMavenpackages_23
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - run: touch starting_verify_SetupNodejs_29
      - run: rm starting_verify_SetupNodejs_29
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: touch starting_verify_RuntheMavenverifyphase_33
      - run: rm starting_verify_RuntheMavenverifyphase_33
      - name: Run the Maven verify phase
        run: mvn verify -Dgpg.skip=true
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: Execute py script # run file
        if: always()
        run: |
          python .github/workflows/script.py
      - name: Pushes analysis to another repository
        if: always()
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'optimizing-ci-builds-ci-analysis'
          destination-github-username: 'UT-SE-Research'
          destination-repository-name: 'ci-analyzes'
          target-branch: '1676344081-be4bc7c'
          target-directory: 'socket.io-client-java/.github/workflows/ci/verify_java_${{ matrix.java }}'
